### ISSUE TITLE
help with your conky

### ISSUE THREAD

**Issue by tjw0lf** [drxspace/cronoconky#2]
I want to change the base where is the base icon for the conky stored. Please help Thank you

**Comment by drxspace** [comment]
```
# Installing application's icon...
echo -en "\nInstaling the “${THISAPPNAME}” icon..."
sudo cp -f "${WIZDIR}"/icons/cronograph256x256.png /usr/share/pixmaps/cronograph.png 2>/dev/null && okay || error
```
I hope this helps

**Comment by tjw0lf** [comment]
so wait where is this one located cronograph256x256.png. All's that i see is this one in pixmaps cronograph.png... I'm looking for the base of this conky which i think is this one cronograph256x256.png

**Comment by drxspace** [comment]
It's in the `icons` folder

**Comment by tjw0lf** [comment]
you mean /usr/share/icons  or somewhere else. becuase i checked there and wasn't in there. I'm just looking for where the conky pulls the base image up from.

**Comment by drxspace** [comment]
Nope, I mean this `https://github.com/drxspace/cronoconky/tree/master/icons`

**Comment by tjw0lf** [comment]
you mean when i download it. But where does it pull the image base from when conky runs on the Linux OS

**Comment by drxspace** [comment]
I can't help you because I don't understand what you mean, sorry.
It is just a screenshot that I edit.

**Comment by tjw0lf** [comment]
i'm talking about the image base for conky. it goes somewhere on the Linux OS. When you ,/start_crono.sh or start which ever way. The whole image appears for base image. The circle. Like for example... in my .conky folder i have conky spotter for spotify music. so in folder covers is the image base transparent image that holds it all together. Then in scripts folder are the rest of the files for spotify and if any lua or stuff. then is the conky config file for text. then when i go and start conky it pulls the image base from the covers folder. in .conky. 

Your cronograph image base no where to be found but it pulls up. I'm trying to change the circle color to blue and make in more transparent. I used gimp changed the color how i want and stuff change the image in icons folder and in pixmaps but that is not the base image when conky starts becuase its still white.

Do you get me now? Hope this helps

**Comment by drxspace** [comment]
the whole drawing is done with `lua`
check this directory `/opt/cronograph_blk`
